import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Featured from "../components/Featured";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Flair</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Featured />
      <About />
      <Contact />
      <Footer />
    </div>
  );
}
